name: Lephix's Blog
description: Better late than never!
url: https://www.lephix.com
timezone: Asia/Shanghai
markdown: kramdown
kramdown:
  input: GFM
theme: minima

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "http://github.com/lephix" }
  header_pages:
    - links.md 
